#!/usr/bin/env python3
"""
Generate skills/external/<id>/SKILL.md and docs/related-github-projects.md
from docs/external-tools.manifest.json.

Run from repo root:
  python3 scripts/generate-external-tool-skills.py
"""
from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs" / "external-tools.manifest.json"
EXTERNAL = ROOT / "skills" / "external"
RELATED_DOC = ROOT / "docs" / "related-github-projects.md"


def load_manifest() -> list[dict]:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    return data["items"]


def skill_description(item: dict) -> str:
    triggers = item["triggers"]
    t = "; ".join(triggers[:6])
    if len(triggers) > 6:
        t += "; …"
    return (
        f"{item['display_name']} — {item['summary']} "
        f"Use when the user mentions or needs: {t}."
    )


def render_skill_md(item: dict) -> str:
    repo = item["repo"]
    url = f"https://github.com/{repo}"
    skill_name = item["id"]
    desc = skill_description(item)
    # YAML frontmatter: description must be safe (no unescaped quotes chaos)
    desc_one_line = desc.replace("\n", " ").strip()
    desc_yaml = json.dumps(desc_one_line)

    skill_origin = (
        "Upstream may publish plugin or skill metadata — prefer upstream for install truth."
        if item.get("upstream_publishes_skill")
        else "Bridge skill generated by ai-skills-library; upstream repo is the product."
    )

    compliance = item.get("compliance_notes") or []
    comp_block = ""
    if compliance:
        comp_block = "\n## Compliance & safety\n\n" + "\n".join(f"- {c}" for c in compliance) + "\n"

    triggers_md = "\n".join(f"- {t}" for t in item["triggers"])

    return f"""---
name: {skill_name}
description: {desc_yaml}
---

# {item["display_name"]}

| | |
|--|--|
| **Upstream** | [{repo}]({url}) |
| **Artifact type** | **{item["artifact_type"]}** (tool / product — not shipped inside this repo) |
| **Skill packaging** | **Generated** in [`skills/external/{skill_name}/`](.) — {skill_origin} |
| **Catalog** | [`../SKILL-CATALOG.md`](../SKILL-CATALOG.md) |

## Bridge skill definition

This is a **bridge skill**: a thin AI Skills Library routing file that teaches
agents when and how to use the upstream product without copying the upstream
product source into this repo.

- **Artifact:** `{repo}` is the real product repository.
- **Bridge:** `skills/external/{skill_name}/SKILL.md` is the agent playbook.
- **Source of truth:** install, API, license, and release details stay upstream.
- **Do not vendor:** this file should point to the product, not duplicate it.

## When to use this skill

{triggers_md}

## Agent playbook

1. **Do not assume the software is installed.** Confirm environment, then give clone/install steps from the upstream README.
2. **Defer API details** (endpoints, env vars, GPU requirements) to upstream docs; link the user there when specifics matter.
3. **Narrow scope:** help with integration planning, architecture, and safe defaults — not a substitute for reading upstream license and ToS.
4. If the user already uses a **native upstream skill** (see table in [`related-github-projects.md`](../../docs/related-github-projects.md)), follow that when it conflicts with this bridge.

## Install / operations

{item["install_pointer"]}
{comp_block}
## Related index

Human-readable table with **Tool vs skill** tags: [`../../docs/related-github-projects.md`](../../docs/related-github-projects.md).

Manifest source (edit to add tools): [`../../docs/external-tools.manifest.json`](../../docs/external-tools.manifest.json).
"""


def write_skills(items: list[dict]) -> None:
    EXTERNAL.mkdir(parents=True, exist_ok=True)
    for item in items:
        d = EXTERNAL / item["id"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "SKILL.md").write_text(render_skill_md(item), encoding="utf-8")


def artifact_label(t: str) -> str:
    return {
        "library": "Library",
        "plugin": "Plugin",
        "platform": "Platform",
        "application": "Application",
        "mcp_server": "MCP server",
        "service": "Service",
    }.get(t, t.replace("_", " ").title())


def write_related_doc(items: list[dict]) -> None:
    # Preserve section order as first seen
    sections: "OrderedDict[str, list[dict]]" = OrderedDict()
    for item in items:
        sections.setdefault(item["section"], []).append(item)

    lines = [
        "# Related GitHub projects",
        "",
        "<!-- GENERATED by scripts/generate-external-tool-skills.py — do not edit by hand; edit docs/external-tools.manifest.json instead -->",
        "",
        "Each row links the **upstream repo** and the **generated bridge skill** in this library (so agents have a `SKILL.md` entry without vendoring the whole product).",
        "",
        "| Column | Meaning |",
        "|--------|---------|",
        "| **Artifact** | What kind of software it is *upstream* (tool/library/service/etc.). |",
        "| **Skill** | **Generated** = `skills/external/<id>/SKILL.md` maintained by codegen from the manifest. **+ upstream** = upstream may also ship plugin/skill metadata; prefer upstream for install. |",
        "",
        "**Licenses, safety, and compliance** are always **upstream** — review before production.",
        "",
    ]

    for section, rows in sections.items():
        lines.append(f"## {section}")
        lines.append("")
        lines.append("| Repo | Artifact | Skill | Notes |")
        lines.append("|------|----------|-------|-------|")
        for item in rows:
            repo = item["repo"]
            url = f"https://github.com/{repo}"
            skill_rel = f"[`{item['id']}`](../skills/external/{item['id']}/SKILL.md)"
            skill_col = "**Generated**" + (" + check upstream" if item.get("upstream_publishes_skill") else "")
            art = artifact_label(item["artifact_type"])
            note = item["summary"].replace("|", "\\|")
            lines.append(f"| [{repo}]({url}) | {art} | {skill_col} · {skill_rel} | {note} |")
        lines.append("")

    lines.extend(
        [
            "## Adding or changing entries",
            "",
            "1. Edit [`external-tools.manifest.json`](external-tools.manifest.json).",
            "2. Run `python3 scripts/generate-external-tool-skills.py`.",
            "3. Run `python3 scripts/generate-skill-catalogs.py` (refreshes `skills/external/SKILL-CATALOG.md`).",
            "4. Commit manifest + generated files together.",
            "",
            "Optional: symlink into Claude Code:",
            "",
            "```bash",
            "./scripts/link-external-skills-to-claude.sh",
            "```",
            "",
        ]
    )
    RELATED_DOC.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    items = load_manifest()
    write_skills(items)
    write_related_doc(items)
    print(f"Wrote {len(items)} skills under {EXTERNAL.relative_to(ROOT)}")
    print(f"Wrote {RELATED_DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
